apiVersion: apps/v1
kind: Deployment
metadata:
  name: appfront
  labels:
    app: apprfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appfront
  template:
    metadata:
      labels:
        app: appfront
    spec:
      containers:
      - name: appfront
        image: hotsapp/appfront
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: appfront
  labels:
    app: appfront
    service: appfront
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: appfront