apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
  labels:
    app: streamer
    version: v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamer
      version: v1
  template:
    metadata:
      labels:
        app: streamer
        version: v1
    spec:
      containers:
      - name: streamer
        image: hotsapp/streamer
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: streamer
  labels:
    app: streamer
    service: streamer
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: streamer