apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: fabiolux/hotsappwebapi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapi
  labels:
    app: webapi
    service: webapi
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: webapi